### ISSUE TITLE
出品授業一覧に出品授業とその授業を申し込みチャットを送った人の一覧表示

### ISSUE THREAD

**Issue by B106827** [teamlaravel/katekyo#3]
テーブルの結合が全然できない・・・

**Comment by Ishikawahiroki** [comment]
Tips共有/
１対多レコードのテーブル結合だから困ってたってことだよね。。。
とりあえず今回は、力技でやりました。
　・「１対多」なので、結合がうまくできなくて俺も諦めた。
　・なので単純にif文で書いた。
　・多重ループの中にif文で実現。（@foreachの中に@foreach、さらにその中でif文）
　・多重ループ回してるけど、そもそも出品者idだけに絞ったレコードを取得してきてるので、そこまで処理重くはならないはず。但し、膨大に出品されて膨大にチャットルームできたらやばそうなコード？？？。
　・おそらくだけど、やり方はいくつかあるような気がする。
